# docker-compose.yml

# version: '3.8'
services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: local
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "1337:1337"
    environment:
      NHOST_SUBDOMAIN: local
      NHOST_REGION: local
      NHOST_POSTGRES_URL: postgres://postgres:postgres@postgres:5432/local
      NHOST_AUTH_URL: http://backend:1337/v1/auth
      NHOST_STORAGE_URL: http://backend:1337/v1/storage
      NHOST_FUNCTIONS_URL: http://backend:1337/v1/functions
      NHOST_DASHBOARD_URL: http://backend:1337
    volumes:
      - ./backend:/app
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NUXT_PUBLIC_NHOST_SUBDOMAIN: local
      NUXT_PUBLIC_NHOST_REGION: local
      NUXT_PUBLIC_NHOST_BACKEND_URL: http://backend:1337/v1
      NUXT_PUBLIC_NHOST_AUTH_URL: http://backend:1337/v1/auth
      NUXT_PUBLIC_NHOST_STORAGE_URL: http://backend:1337/v1/storage
      NUXT_PUBLIC_NHOST_FUNCTIONS_URL: http://backend:1337/v1/functions
      NUXT_PUBLIC_NHOST_DASHBOARD_URL: http://backend:1337
      NUXT_PUBLIC_NHOST_POSTGRES_URL: postgres://postgres:postgres@postgres:5432/local
      APP_TITLE: Gestion des cantines scolaires 2025
      APP_DESCRIPTION: Gestion des cantines scolaires 2025.
      APP_LOGO: /logo.png
      BASE_URL: http://localhost:3000
      PORT: 3000
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

volumes:
  postgres_data:
